name: Build & Push Docker (on tag)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build jar
        run: mvn -B -DskipTests package

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag/version
        id: vars
        run: |
          echo "TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: To lowercase owner
        id: repo
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            APP_VERSION=${{ steps.vars.outputs.TAG }}
          tags: |
            ghcr.io/${{ steps.repo.outputs.OWNER_LC }}/watermelon:${{ steps.vars.outputs.TAG }}
            ghcr.io/${{ steps.repo.outputs.OWNER_LC }}/watermelon:latest